server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-product-indi
    username: postgres #${DB_USER} #postgres  #AGREGAR .ENV  DE PRODUCT A LAS CONFIGURACIONES DEL RUN DE PRODUCT.
    password: sasa #${DB_PASS} #sasa
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # DESPLIEGA EL CONTENEDOR DE RABBIT
  # docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4-management
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #zipkin
  tracing:
    sampling:
      probability: 1.0

#  http://localhost:8081/actuator/busrefresh


app:
  message: "--- HELLO MS PRODUCT up ---"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7