spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${DB_MONGO} #db-user-indi
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

  #http://localhost:8082/actuator/busrefresh